# Generated by Django 5.0.6 on 2024-06-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_comment="Auto created ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Auto created ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_comment="User Password",
                        max_length=64,
                        verbose_name="Password",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Last login time",
                        null=True,
                        verbose_name="Last login time",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        db_comment="Administrator status",
                        default=False,
                        verbose_name="Administrator status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_comment="ID to use when login for the user",
                        max_length=16,
                        unique=True,
                        verbose_name="ID to use when login",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="The user's real name",
                        max_length=30,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="The user's email address",
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="In-service status",
                        default=True,
                        verbose_name="In-service status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="The date the user joined",
                        verbose_name="Joined Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
        ),
    ]
