# Generated by Django 5.0.6 on 2024-06-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                db_comment="The user's real name",
                max_length=30,
                verbose_name="The user's real name",
            ),
        ),
    ]
