# Generated by Django 5.0.6 on 2024-06-28 02:12

import django.core.serializers.json
import django.db.models.deletion
import json.decoder
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationChatbotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        db_comment="Chatbot body body for Education AI",
                        decoder=json.decoder.JSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Chatbot body for Education AI",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Created Time",
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="User's ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                        verbose_name="User's ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Chatbot Log",
                "verbose_name_plural": "Education Chatbot Log",
                "db_table": "education_chatbot_log",
            },
        ),
        migrations.CreateModel(
            name="EducationQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        db_comment="Quiz for Education",
                        decoder=json.decoder.JSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Quiz for Education",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Created Time",
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="User's ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                        verbose_name="User's ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Quiz",
                "verbose_name_plural": "Education Quiz",
                "db_table": "education_quiz",
            },
        ),
    ]
