# Generated by Django 5.0.6 on 2024-06-28 01:59

import django.core.serializers.json
import django.db.models.deletion
import json.decoder
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_comment="Counsel Manual Category",
                        max_length=24,
                        verbose_name="Counsel Manual Category",
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        db_comment="Counsel Manual body for Counselor",
                        decoder=json.decoder.JSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Counsel Manual body for Counselor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counsel Manual",
                "verbose_name_plural": "Counsel Manual",
                "db_table": "counsel_manual",
            },
        ),
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                (
                    "phone_number",
                    models.CharField(
                        db_comment="Customer's Korea Phone Number",
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Customer's Korea Phone Number",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Customer's Name",
                        max_length=24,
                        verbose_name="Customer's Name",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        db_comment="Customer's Birth Date",
                        verbose_name="Customer's Birth Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Info",
                "verbose_name_plural": "Customer Info",
                "db_table": "customer_info",
            },
        ),
        migrations.CreateModel(
            name="CounselChatbotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        db_comment="Chatbot body body for Counselor",
                        decoder=json.decoder.JSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Chatbot body for Counselor",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Created Time",
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_comment="User's ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                        verbose_name="User's ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counsel Chatbot Log",
                "verbose_name_plural": "Counsel Chatbot Log",
                "db_table": "counsel_chatbot_log",
            },
        ),
        migrations.CreateModel(
            name="CounselLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_comment="Account's Username",
                        max_length=16,
                        verbose_name="Account's Username",
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        db_comment="Counsel Body(JSON Format)",
                        decoder=json.decoder.JSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Counsel Body(JSON Format)",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Created Time",
                        verbose_name="Created Time",
                    ),
                ),
                (
                    "memo",
                    models.JSONField(
                        db_comment="Noted By Counselor",
                        decoder=json.decoder.JSONDecoder,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="Noted By Counselor",
                    ),
                ),
                (
                    "phone_number",
                    models.ForeignKey(
                        db_column="phone_number",
                        db_comment="Customer's Korea Phone Number(from customer_info)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counseling.customerinfo",
                        verbose_name="Customer's Korea Phone Number(from customer_info)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counsel Log",
                "verbose_name_plural": "Counsel Log",
                "db_table": "counsel_log",
            },
        ),
    ]
